### ISSUE TITLE
Steering improvements and obstacle avoidance

### ISSUE THREAD

**Issue by DimitrisPok** [DIT113-V22/group-11#19]
We tried out different ways to avoid obstacles and prevent crashing to see what the best implementation was. One of the things we tried was to make the car stop at different distances from the obstacle. Another option we had was to make the car start moving backward when it encounters an obstacle. One option that we are yet to try is to make the car go the opposite way of the object that the sensors detect and could possibly be a threat to our car.

**Comment by jenniferhalgh** [comment]
Added a description to the issue.

**Comment by shahdmetwally** [comment]
Done!
