### ISSUE TITLE
Manual steering

### ISSUE THREAD

**Issue by SadhanaAnandan** [DIT113-V22/group-11#31]
As a user, I want to control the car's speed, so that I can accelerate the car as I wish.

Acceptance criteria: 

- [x] The car should move faster as the joystick is moved further away from the centre of the joystick. 
- [x] The speed of the car should be zero when the joystick is in the centre.
- [x] The maximum speed the car can achieve when the joystick is furthest away is 1 m/s.

**Comment by Gussamanel** [comment]
This has been completed.

**Comment by shahdmetwally** [comment]
This issue is not accurate to our system.
