### ISSUE TITLE
Fix obstacle avoidance bug

### ISSUE THREAD

**Issue by jenniferhalgh** [DIT113-V22/group-11#53]
There is a bug with obstacle avoidance, sometimes when you meet an obstacle you can't move at all when it should allow the user to be able to move to avoid the obstacle.  The car might stop even when obstacles are far away from it and wont turn towards any direction with the only solution to the problem being to reset the position of the car and start again. 

- [x] The car no longer stopes moving away from an obstacle when the sensors detect one.
- [x] The bug fix does not make the cars obstacle avoidance less trustable.
- [x] The solution has been tested on both the app and SMCE alone to make sure that no problems may occur from the apps perspective.

**Comment by DimitrisPok** [comment]
The bug has now been fixed thanks to the latest changes to the Arduino sketch. The issue can now be closed.
