### ISSUE TITLE
Map view and environment

### ISSUE THREAD

**Issue by jenniferhalgh** [DIT113-V22/group-11#6]
As a user, I want to have a pleasant time when trying to navigate through the map with my car.

Acceptance Criteria:

- [x] The user must view the car in a consistent third person view.
- [x] The user will be able to navigate towards all directions on the map with no restrains. 
- [x] The car movements should be smooth and realistic.  
- [x] The vehicle should be able to avoid crashing with obstacles by using ultrasonic sensors.

**Comment by SadhanaAnandan** [comment]
This issue is no longer part of this project, it was for the old project and was thus closed.
