### ISSUE TITLE
Maintaining phone connections

### ISSUE THREAD

**Issue by Gussamanel** [DIT113-V22/group-11#7]
As a user, I want to be able to have a stable connection to the car, through my device, so that I can drive the car without any glitches or interruptions. 

Acceptance Criteria: 

- [x] The device should have a stable connection to the emulator for at least 2 whole minutes. 
- [x] The device will be able to send commands to the emulator.

**Comment by shahdmetwally** [comment]
We are done with this! It went well we have established connection!
