### ISSUE TITLE
Application layout

### ISSUE THREAD

**Issue by AnashaSarker2001** [DIT113-V22/group-11#8]
As a user, I want to have a pleasant layout that has no visual or physical strain.

Acceptance Criteria:
- [x] The color palette should be aesthetically pleasing and not visually straining( it should not include contrasting/bright colors). 
- [x] The layout should not be too crowded/overwhelming. 
- [x] All the functions should be easily accessible.

**Comment by shahdmetwally** [comment]
We are done with the application layout.
