### ISSUE TITLE
:warning: Missing Arduino CI

### ISSUE THREAD

**Issue by platisd** [DIT113-V22/group-11#80]
1. You have multiple Arduino sketches on `master`. Why is that? Do you need all of them? If you don't need some remove it, don't keep it on `master`.
2. Not every Arduino sketch currently on `master` is built on CI.

Please address the above immediately and pay closer attention to this in the future.

**Comment by platisd** [comment]
Specifically:
* [cmake-build-debug](https://github.com/DIT113-V22/group-11/tree/master/arduino/cmake-build-debug) should be removed and then gitignore'd
* [libraries](https://github.com/DIT113-V22/group-11/tree/master/arduino/libraries) should be removed and then gitignore'd
* Decide on whether you need [SMCE_ultrasonic_sensor](https://github.com/DIT113-V22/group-11/tree/master/arduino/SMCE_ultrasonic_sensor) or [smartcar](https://github.com/DIT113-V22/group-11/tree/master/arduino/smartcar) and remove what is not needed. Make sure what remains on `master` is built on CI.

**Comment by shahdmetwally** [comment]
I am trying to remove one of the arduino sketches we have on the master branch however it keeps failing the arduino CI check. Do you have any idea why this would be the case? The sketch we are trying to delete is the sketch from the obstacle avoidance assignment we were assigned at the beginning of the course therefore we will not be needing it on our repository.

**Comment by platisd** [comment]
You should modify the Arduino workflow to build the sketc(es) you actually use instead.

**Comment by platisd** [comment]
Two tasks left:
- [ ] Remove `libraries`
- [ ] Make your sketch build on CI
